analytics:
  ua: ''
  gtag: ''
  gtm: ''
  ga_prod: ''
breadcrumbs:
  goal:
    - path: /
      label: general.home
  indicator:
    - path: /
      label: general.home
  post:
    - path: /
      label: general.home
    - path: /news
      label: menu.updates
cookie_consent_form:
  enabled: false
country:
  name: Malta
  adjective: Maltese
create_goals:
  previous_next_links: false
  goal_content_heading: ''
  goals: []
create_indicators:
  previous_next_links: true
create_pages:
  - filename: ''
    folder: /reporting-status
    layout: reportingstatus
    title: status.reporting_status
  - filename: ''
    folder: /search
    layout: search
    title: search.search
  - filename: ''
    folder: /maps
    layout: maps
    title: Maps
custom_css: []
custom_js:
  - /assets/js/custom.js
data_edit_url: ''
data_fields:
  units: ''
  series: ''
date_formats: []
disclaimer:
  hidden: true
email_contacts:
  questions: cmu.nso@gov.mt
  suggestions: cmu.nso@gov.mt
  functional: it.nso@gov.mt
empty_metadata_placeholder: ''
empty_metadata_placeholder_sources: ''
environment: staging
footer_language_toggle: none
footer_menu:
  - path: /contact-us
    translation_key: menu.contact_us
  - path: 'https://x.com/NSOMALTA'
    translation_key: X
  - path: 'https://www.facebook.com/nsomalta/'
    translation_key: general.facebook
  - path: /about/cookies-and-privacy/
    translation_key: menu.cookies
frontpage_cards:
  - title: frontpage.download_all
    content: ''
    include: components/download-all-data.html
    button_label: ''
    button_link: ''
    rule_color: ''
  - title: SDGs in Malta
    content: |
      <ul>
        <li><a href="https://nso.gov.mt/themes_publications/transport-statistics-2021-3/">SDG Publication: 2021 edition</a></li>
        <li><a href="https://sustainabledevelopment.gov.mt/vnr/">Malta's Second Voluntary National Review</a></li>
        <li><a href="https://sustainabledevelopment.gov.mt/maltas-sustainable-development-strategy-for-2050/">Malta's Sustainable Development Strategy</a></li>
        <li><a href="https://sustainabledevelopment.gov.mt/vision-2050/">Malta's Sustainable Development Vision</a></li> 
      </ul>
    include: ''
    button_label: ''
    button_link: ''
    rule_color: ''
  - title: International Resources
    content: |
      <ul>
        <li><a href="https://unstats.un.org/sdgs/dataportal/database">UN SDG Database</a></li>
        <li><a href="https://unstats.un.org/sdgs/report/2024/">UN SDG Report 2024</a></li>
        <li><a href="https://ec.europa.eu/eurostat/en/web/products-flagship-publications/w/ks-01-24-018">Sustainable development in the European Union - 2025 Edition</a></li>
        <li><a href="https://ec.europa.eu/eurostat/cache/visualisations/sdgs/">Eurostat: SDGs & me</a></li>       
      </ul>
    include: ''
    button_label: ''
    button_link: ''
    rule_color: ''
frontpage_goals_grid:
  title: frontpage.heading_short
  description: frontpage.instructions_shorter
frontpage_introduction_banner:
  title: frontpage.intro_title
  description: |
    [The Sustainable Development Goals (SDGs)](https://www.un.org/sustainabledevelopment/sustainable-development-goals/) are a universal call to action to end poverty, protect the planet and improve the lives and prospects of everyone, everywhere. The 17 Goals were adopted by all UN Member States in 2015, as part of the [2030 Agenda for Sustainable Development](https://sdgs.un.org/2030agenda).
goal_image_base: 'https://open-sdg.org/sdg-translations/assets/img/goals'
goal_image_extension: ''
goals_page:
  title: general.goals
  description: frontpage.instructions_shorter
graph_color_headline: '#004466'
graph_color_headline_high_contrast: '#55a6e5'
graph_color_set: custom
graph_color_list: ['D32F2F','4CAF50', '7B1FA2', '1976D2', 'FFEB3B', '795548', 'FF9800', 'E91E63', '512DA8', 'CDDC39', '455A64', 'FF5722', '42d4f4', 'aaffc3','800000']
graph_color_number: 15
graph_title_from_series: false
header_language_toggle: dropdown
hide_empty_metadata: true
hide_single_series: true
hide_single_unit: true
ignored_disaggregations: []
indicator_config_form:
  enabled: false
  dropdowns: []
  repository_link: /tree/develop/indicator-config
  translation_link: ''
indicator_data_form:
  enabled: false
  repository_link: /tree/develop/data
indicator_metadata_form:
  enabled: false
  dropdowns: []
  repository_link: /tree/develop/meta
  translation_link: ''
  language: en
  scopes:
    - national
    - global
  exclude_fields: []
  translated: false
indicator_tabs:
  tab_1: ''
  tab_2: ''
  tab_3: ''
  tab_4: ''
languages:
  - en
languages_public: []
logos: []
map_layers: []
menu:
  - path: /
    translation_key: general.home
    dropdown: []
  - path: /maps
    translation_key: Maps
    dropdown: []
  - path: /reporting-status
    translation_key: menu.reporting_status
    dropdown: []
  - path: /news
    translation_key: menu.updates
    dropdown: []
  - path: /faq
    translation_key: menu.faq
    dropdown: []
  - path: /about
    translation_key: menu.about
    dropdown: []
metadata_edit_url: ''
metadata_tabs: []
meta_tags:
  - path: ''
    name: description
    content: Sustainable Development Indicators Malta
  - path: ''
    name: keywords
    content: SDG, SDGs, sdg, sdgs, Malta, NSO, Sustainable development goals, Sustainable development, Sustainable Development Indictors, SDG data, SDI, SDIs, sdis, indicators, data, goals
news:
  category_links: false
progress_status:
  status_heading: ''
  status_help: ''
  status_types: []
progressive_web_app:
  enabled: false
  name: ''
  short_name: ''
  precaching: false
proxy_indicators:
  label: ''
  description: ''
remote_data_prefix: 'https://nsomalta.github.io/sdgdata/'
reporting_status:
  title: status.reporting_status
  description: status.description
  disaggregation_tabs: false
  status_types:
    - value: notstarted
      label: status.no_data_available
      hide_on_goal_pages: false
    - value: complete
      label: status.reported_online
      hide_on_goal_pages: false
    - value: notapplicable
      label: status.not_applicable
      hide_on_goal_pages: false
    - value: inprogress
      label: In Progress
      hide_on_goal_pages: false
repository_url_data: 'https://github.com/NSOMalta/sdgdata'
repository_url_site: 'https://github.com/NSOMalta/sdgsite'
search_index_boost: []
search_index_extra_fields: []
site_config_form:
  enabled: true
  dropdowns: []
  repository_link: /tree/develop/_data
  translation_link: ''
time_series_attributes:
  - field: COMMENT_TS
    label: indicator.footnote
  - field: DATA_LAST_UPDATE
    label: metadata_fields.national_data_update_url
use_new_config_forms: false
validate_indicator_config: false
validate_site_config: false
x_axis_label: ''
